In [2]:
import pandas as pd
import random

In [3]:
# Population
# todos los datos son por semana
# los fake data tiemen que cumplicar los validation rules

xlsx = 'IDS_AGG_1.2.0_DHIS2.39/IDS_AGG_COMPLETE_1.2.0_DHIS2.39/IDS_AGG_COMPLETE_1.2.0_DHIS2.39.xlsx'
sheet_1 = 'dataElements'
sheet_2 = 'validationRules'
dataElements = pd.read_excel(xlsx,sheet_1)
validationRules = pd.read_excel(xlsx,sheet_2)

In [4]:
import random


def auth_dhis(url):
    url = url+ "/api/me"
    session = requests.Session()
    session.auth = ('admin', 'district')
    return session

def gen_fake_one_data(population,valueType, max_range):  
    # TODO not sure bout NUMBER valuetype data
    ratio = random.uniform(0,max_range)
    while valueType == 'INTEGER_ZERO_OR_POSITIVE' and ratio ==0:
        ratio = random.uniform(0,max_range)
    return round(ratio*population)

def gen_data_fake_dataframe(population,df,max_range):
    fake_data = []
    for _,row in df.iterrows():
        fake_data.append(gen_data(population,row['valueType'],max_range))
    df['value'] = fake_data 
    return df


def build_dataElement_bulk_json(period,date,org_unit,dataSet,df):
    data = df.loc[:,['id','value']]
    data = data.rename(columns = {'id':'dataElement'})
    data = data.astype(str)
    data_dict = data.to_dict('records') 
    req = {"dataSet": dataSet,
    "completeDate": date,
    "orgUnit": org_unit,
    "period":period,
    "dataValues": data_dict
                }
    return req

# generación de datos dados por Chat GPT4
import pandas as pd
import numpy as np

def generate_malaria_data():
    # Definir una lista con las tres regiones
    regions = ['Dakar', 'Diourbel', 'San Luis']
    
    # Generar datos de malaria aleatorios para cada región utilizando la distribución normal
    dakar_data = np.random.normal(loc=50, scale=10, size=52).astype(int)
    diourbel_data = np.random.normal(loc=80, scale=20, size=52).astype(int)
    san_luis_data = np.random.normal(loc=30, scale=5, size=52).astype(int)
    
    # Crear un diccionario con los datos y las regiones
    data_dict = {'Region': regions*52,
                 'Semana': np.repeat(np.arange(1,53), 3),
                 'Enfermos de malaria': np.concatenate((dakar_data, diourbel_data, san_luis_data))}
    
    # Crear un DataFrame a partir del diccionario
    malaria_df = pd.DataFrame(data_dict)
    
    return malaria_df

def generate_fake_data(org_units):
    
    d = list()
    for i in org_units:
        d.append({"org": i,
            "loc" : np.random.uniform(30,80),
            "scale" : np.random.uniform(1,50)})
    random_list = list()
    orgs_unit_list = list()
    week_list = list()
    for i in d:
        random_list.extend(np.random.normal(loc=50, scale=10, size=52).astype(int))
        orgs_unit_list.extend([i["org"]]*52)
        week_list.extend(["2023W" + str(n) for n in  range(1,53)])
        data_dict = {'org_unit': orgs_unit_list,
                'week':week_list,
                "dataValue" : random_list
                    }
    fake_data_df = pd.DataFrame.from_dict(data_dict)
    return fake_data_df
            
        

import datetime

def generate_day_a_week(year,week_day_number):
    start_date = datetime.date(year, 1, 1)  # primer día del año
    end_date = datetime.date(year, 12, 31)  # último día del año
    delta = datetime.timedelta(days=1)

    week_day = []
    current_date = start_date

    while current_date <= end_date:
        if current_date.weekday() == week_day_number:  # 0 es lunes
            week_day.append(current_date.strftime('%Y-%m-%d'))
        current_date += delta

    return week_day

In [7]:
weeks = generate_week_periods(2022, 1)
periods = {k: v for k, v in zip(weeks, mondays)}

NameError: name 'generate_week_periods' is not defined

In [146]:
weeks

['Week 2022 1W52',
 'Week 2022 2W01',
 'Week 2022 3W02',
 'Week 2022 4W03',
 'Week 2022 5W04',
 'Week 2022 6W05',
 'Week 2022 7W06',
 'Week 2022 8W07',
 'Week 2022 9W08',
 'Week 2022 10W09',
 'Week 2022 11W10',
 'Week 2022 12W11',
 'Week 2022 13W12',
 'Week 2022 14W13',
 'Week 2022 15W14',
 'Week 2022 16W15',
 'Week 2022 17W16',
 'Week 2022 18W17',
 'Week 2022 19W18',
 'Week 2022 20W19',
 'Week 2022 21W20',
 'Week 2022 22W21',
 'Week 2022 23W22',
 'Week 2022 24W23',
 'Week 2022 25W24',
 'Week 2022 26W25',
 'Week 2022 27W26',
 'Week 2022 28W27',
 'Week 2022 29W28',
 'Week 2022 30W29',
 'Week 2022 31W30',
 'Week 2022 32W31',
 'Week 2022 33W32',
 'Week 2022 34W33',
 'Week 2022 35W34',
 'Week 2022 36W35',
 'Week 2022 37W36',
 'Week 2022 38W37',
 'Week 2022 39W38',
 'Week 2022 40W39',
 'Week 2022 41W40',
 'Week 2022 42W41',
 'Week 2022 43W42',
 'Week 2022 44W43',
 'Week 2022 45W44',
 'Week 2022 46W45',
 'Week 2022 47W46',
 'Week 2022 48W47',
 'Week 2022 49W48',
 'Week 2022 50W49',
 'Week 2022 51W50',
 'Week 2022 52W51',
 'Week 2022 53W52']

In [111]:
week_2 = [ '2023W10',
 '2023W11',
 '2023W12',
 '2023W13',
 '2023W14',
 '2023W15',
 '2023W16',
 '2023W17',
 '2023W18',
 '2023W19',
 '2023W20',
 '2023W21',
 '2023W22',
 '2023W23',
 '2023W24',
 '2023W25',
 '2023W26',
 '2023W27',
 '2023W28',
 '2023W29',
 '2023W30',
 '2023W31',
 '2023W32',
 '2023W33',
 '2023W34',
 '2023W35',
 '2023W36',
 '2023W37',
 '2023W38',
 '2023W39',
 '2023W40',
 '2023W41',
 '2023W42',
 '2023W43',
 '2023W44',
 '2023W45',
 '2023W46',
 '2023W47',
 '2023W48',
 '2023W49',
 '2023W50',
 '2023W51',
 '2023W52']

In [99]:
org_units_sen = ["y9Klh0O59vB",
"W8ZmxXgvCkY",
"kJIGh9lW8a8",
"UeC7s1uajH8",
"E24bLyrjfPI",
"xYhOeNPEaHg",
"BBKMl3wPek3",
"Sx7WMf3JxPL",
"u3qWtYM1nMY",
"Nekj896sgXP",
"vE39as9Ji6J",
"nhEFDv2BoVO",
"qbcz4wAp08p",
"LkwyLAppt46"]
senegal_population = {
    'Dakar': 3120000,
    'Diourbel': 1410000,
    'Fatick': 640000,
    'Kaffrine': 554000,
    'Kaolack': 1119000,
    'Kédougou': 171000,
    'Kolda': 831000,
    'Louga': 873000,
    'Matam': 605000,
    'Saint-Louis': 939000,
    'Sédhiou': 451000,
    'Tambacounda': 858000,
    'Thiès': 1864000,
    'Ziguinchor': 621000
}

org_units = {
    "id" : org_units_sen,
    "name" : list(senegal_population.keys()),
    "pop" : list(senegal_population.values())
}

In [154]:
fake_data_all = generate_fake_data(org_units_sen)
fake_data = gen_data_fake_dataframe_per_dataElements(Diurbel_pop,dataElements,0.03)

NameError: name 'df' is not defined

In [118]:
dataValue =build_dataElement_bulk_json("2023W03","2023-01-17","y9Klh0O59vB","OTvkNTijYQY",fake_data)

In [119]:
dataValue

{'dataSet': 'OTvkNTijYQY',
 'completeDate': '2023-01-17',
 'orgUnit': 'y9Klh0O59vB',
 'period': '2023W03',
 'dataValues': [{'dataElement': 'DkmMEcubiPv', 'value': '2'},
  {'dataElement': 'cPLAnOTldta', 'value': '2'},
  {'dataElement': 'iLEkjJcYTJd', 'value': '1'},
  {'dataElement': 'WpKu7cyd7Zo', 'value': '1'},
  {'dataElement': 'KY2gR9npnfP', 'value': '1'},
  {'dataElement': 'P666FBECG0N', 'value': '3'},
  {'dataElement': 'yCjneRUc565', 'value': '3'},
  {'dataElement': 'qYJ3YYLADtz', 'value': '0'},
  {'dataElement': 'bXn9Kmxnd3r', 'value': '2'},
  {'dataElement': 'my2vljFIgT3', 'value': '4'},
  {'dataElement': 'flD9dHHw3Wl', 'value': '0'},
  {'dataElement': 'mhh4tZRqbf8', 'value': '3'},
  {'dataElement': 'FTWXeWdPdVH', 'value': '4'},
  {'dataElement': 'miZ7nLeBp1w', 'value': '4'},
  {'dataElement': 'fVYqPV4Yfuv', 'value': '0'},
  {'dataElement': 'Gn5FOQygSJM', 'value': '2'},
  {'dataElement': 'Sc5efRwnOA9', 'value': '1'},
  {'dataElement': 'j3t0jhGOHhP', 'value': '2'},
  {'dataElement': 'unXcJLrNYNe', 'value': '0'},
  {'dataElement': 'vd4GxqtKkRC', 'value': '1'},
  {'dataElement': 'wryMP8p8k1C', 'value': '0'},
  {'dataElement': 'ZYvr5OITjBa', 'value': '2'},
  {'dataElement': 'jxvt8LFSx8e', 'value': '3'},
  {'dataElement': 'ddGAKVfTvlQ', 'value': '3'},
  {'dataElement': 'juTM5EM0Jo0', 'value': '1'},
  {'dataElement': 'qFGp7kAZ5Me', 'value': '4'},
  {'dataElement': 'X4gFcPKQ8Cw', 'value': '3'},
  {'dataElement': 'Hrsq0RqGFKO', 'value': '2'},
  {'dataElement': 'yMlASPYVU2v', 'value': '3'},
  {'dataElement': 'Z1lCDUuuuHg', 'value': '1'},
  {'dataElement': 'qNsd9cPWNVo', 'value': '1'},
  {'dataElement': 'mZ08SCurQVX', 'value': '1'},
  {'dataElement': 'UXtfpFrG53k', 'value': '1'},
  {'dataElement': 'RGmtcR1mcfn', 'value': '2'},
  {'dataElement': 'K2Ky3gBe2sB', 'value': '1'},
  {'dataElement': 'IwElS2y8uzq', 'value': '1'},
  {'dataElement': 'e27MJXqMPAW', 'value': '2'},
  {'dataElement': 'Nj943YZm5J0', 'value': '4'},
  {'dataElement': 'I0hSJHycgzT', 'value': '4'},
  {'dataElement': 'McxtlIwrSYl', 'value': '1'},
  {'dataElement': 'D5nYQAs4YYN', 'value': '0'},
  {'dataElement': 'ZcuZSS8QHOg', 'value': '2'},
  {'dataElement': 'paABbIxQ6fI', 'value': '1'},
  {'dataElement': 'LNOSbgZiqaJ', 'value': '1'},
  {'dataElement': 'J0s9X6GHsOi', 'value': '3'},
  {'dataElement': 'U9azl7BliKu', 'value': '1'},
  {'dataElement': 'm2afIjMnymV', 'value': '3'},
  {'dataElement': 'KUuKOtxzBJ1', 'value': '2'},
  {'dataElement': 'RGXZgVrOQyo', 'value': '4'},
  {'dataElement': 'qAM23M0qOId', 'value': '1'},
  {'dataElement': 'lTiuuQij9HP', 'value': '3'},
  {'dataElement': 'f45l3xKDAPs', 'value': '0'},
  {'dataElement': 'dKzr3MsO9kG', 'value': '1'},
  {'dataElement': 'PIeQekpD664', 'value': '2'},
  {'dataElement': 'v2FeCwrKNt5', 'value': '1'},
  {'dataElement': 'I5V4NUxtTre', 'value': '1'},
  {'dataElement': 'RAQCr5DpCzC', 'value': '0'},
  {'dataElement': 'bHSkKIwVBay', 'value': '1'},
  {'dataElement': 'iuh5hm4RVBR', 'value': '2'},
  {'dataElement': 'qqqAULiKFu2', 'value': '1'},
  {'dataElement': 'rl1SLaRmaZ4', 'value': '1'},
  {'dataElement': 'f3MTBlkGjZw', 'value': '4'},
  {'dataElement': 'MbAkHOTlcyp', 'value': '4'},
  {'dataElement': 'n1iUA7kb0wj', 'value': '3'},
  {'dataElement': 'lo0rfBSWDbf', 'value': '3'},
  {'dataElement': 'rVi7C4a14jp', 'value': '3'},
  {'dataElement': 'ZOVJGcrCdCH', 'value': '2'},
  {'dataElement': 'BSyp9DU4HWn', 'value': '3'},
  {'dataElement': 'ezlLC4UCA2g', 'value': '3'},
  {'dataElement': 'hi5J0vMBrbE', 'value': '3'},
  {'dataElement': 'FMM88mSULsl', 'value': '3'},
  {'dataElement': 'I11IpNMGxaR', 'value': '2'},
  {'dataElement': 'sjd8VtIZxmz', 'value': '2'},
  {'dataElement': 'KGWccjjpSdP', 'value': '3'},
  {'dataElement': 'Q1xDDDusLwl', 'value': '1'},
  {'dataElement': 'v1n8aztMcYN', 'value': '3'},
  {'dataElement': 'XRFwVZNgo0p', 'value': '2'},
  {'dataElement': 'b0IzLHcVdm0', 'value': '1'},
  {'dataElement': 'lXepqiS7wQi', 'value': '3'},
  {'dataElement': 'dbdfZyjDco2', 'value': '1'},
  {'dataElement': 'k2hYvS8LTFl', 'value': '0'},
  {'dataElement': 'xfkxDz03AFK', 'value': '1'},
  {'dataElement': 'PR3HRX1IEBj', 'value': '2'},
  {'dataElement': 'KNruIU8QeKP', 'value': '1'},
  {'dataElement': 'LszjUZCLWP2', 'value': '4'},
  {'dataElement': 'BYXzAABOEbr', 'value': '2'},
  {'dataElement': 'I3570OWVcKN', 'value': '3'},
  {'dataElement': 'ClUDerxOIWR', 'value': '4'},
  {'dataElement': 'jUaZniVe1Uq', 'value': '0'}]}

In [84]:
fake_data.loc[(fake_data["week"] == "2023W10") & (fake_data["org_unit"] == "y9Klh0O59vB")]

      org_unit     week  dataValue
9  y9Klh0O59vB  2023W10         39

In [121]:
import requests
import json

def post_data_value_sets(data_value_sets):
    # Login
    url = "http://localhost:8080/api/me"
#     payload = {"username": "admin", "password": "district"}
    session = requests.Session()
    session.auth = ('admin', 'district')

    # Post data value sets
    url = "http://localhost:8080/api/dataValueSets"
    headers = {"Content-Type": "application/json"}
    response = session.put(url, json=data_value_sets, headers=headers)

    # Check if posting was successful
    if response.status_code == 200:
        print("Data value sets posted successfully")
    else:
        print("Posting data value sets failed") 
        print(json.loads(response.text))
          
    return response

# Example usage
# data_value_sets = {"dataValues": [{"dataElement": "DE1", "value": "10"}, {"dataElement": "DE2", "value": "20"}]} 
# post_data_value_sets(data_value_sets)

In [143]:
import json
for week in "2022W20":
    n = 0
    for org in org_units['id']:    
        fake_df = gen_data_fake_dataframe_per_dataElements(org_units["pop"][n],dataElements,0.03)
        dataValue = build_dataElement_bulk_json(week,periods[week],org,"OTvkNTijYQY",fake_df)
        n = +1
        response = post_data_value_sets(dataValue)

NameError: name 'df' is not defined

In [113]:

dataValue

{'dataSet': 'OTvkNTijYQY',
 'completeDate': '2023-12-25',
 'orgUnit': 'LkwyLAppt46',
 'period': '2023W52',
 'dataValues': [{'dataElement': 'DkmMEcubiPv', 'value': '16513293'},
  {'dataElement': 'cPLAnOTldta', 'value': '20740549'},
  {'dataElement': 'iLEkjJcYTJd', 'value': '22018546'},
  {'dataElement': 'WpKu7cyd7Zo', 'value': '22325765'},
  {'dataElement': 'KY2gR9npnfP', 'value': '33463329'},
  {'dataElement': 'P666FBECG0N', 'value': '12611719'},
  {'dataElement': 'yCjneRUc565', 'value': '6376836'},
  {'dataElement': 'qYJ3YYLADtz', 'value': '35116901'},
  {'dataElement': 'bXn9Kmxnd3r', 'value': '14609976'},
  {'dataElement': 'my2vljFIgT3', 'value': '4036349'},
  {'dataElement': 'flD9dHHw3Wl', 'value': '42085259'},
  {'dataElement': 'mhh4tZRqbf8', 'value': '28153855'},
  {'dataElement': 'FTWXeWdPdVH', 'value': '28871371'},
  {'dataElement': 'miZ7nLeBp1w', 'value': '20328647'},
  {'dataElement': 'fVYqPV4Yfuv', 'value': '2474284'},
  {'dataElement': 'Gn5FOQygSJM', 'value': '36411716'},
  {'dataElement': 'Sc5efRwnOA9', 'value': '7285363'},
  {'dataElement': 'j3t0jhGOHhP', 'value': '27861191'},
  {'dataElement': 'unXcJLrNYNe', 'value': '2428073'},
  {'dataElement': 'vd4GxqtKkRC', 'value': '24689744'},
  {'dataElement': 'wryMP8p8k1C', 'value': '2020172'},
  {'dataElement': 'ZYvr5OITjBa', 'value': '29781592'},
  {'dataElement': 'jxvt8LFSx8e', 'value': '513101'},
  {'dataElement': 'ddGAKVfTvlQ', 'value': '34311601'},
  {'dataElement': 'juTM5EM0Jo0', 'value': '9771887'},
  {'dataElement': 'qFGp7kAZ5Me', 'value': '28502244'},
  {'dataElement': 'X4gFcPKQ8Cw', 'value': '25398671'},
  {'dataElement': 'Hrsq0RqGFKO', 'value': '36978490'},
  {'dataElement': 'yMlASPYVU2v', 'value': '1952627'},
  {'dataElement': 'Z1lCDUuuuHg', 'value': '36443238'},
  {'dataElement': 'qNsd9cPWNVo', 'value': '29748762'},
  {'dataElement': 'mZ08SCurQVX', 'value': '6620342'},
  {'dataElement': 'UXtfpFrG53k', 'value': '34242758'},
  {'dataElement': 'RGmtcR1mcfn', 'value': '26613212'},
  {'dataElement': 'K2Ky3gBe2sB', 'value': '21632040'},
  {'dataElement': 'IwElS2y8uzq', 'value': '1898253'},
  {'dataElement': 'e27MJXqMPAW', 'value': '29570762'},
  {'dataElement': 'Nj943YZm5J0', 'value': '13042068'},
  {'dataElement': 'I0hSJHycgzT', 'value': '40846442'},
  {'dataElement': 'McxtlIwrSYl', 'value': '23281398'},
  {'dataElement': 'D5nYQAs4YYN', 'value': '19561758'},
  {'dataElement': 'ZcuZSS8QHOg', 'value': '21925131'},
  {'dataElement': 'paABbIxQ6fI', 'value': '20381561'},
  {'dataElement': 'LNOSbgZiqaJ', 'value': '5085941'},
  {'dataElement': 'J0s9X6GHsOi', 'value': '25918371'},
  {'dataElement': 'U9azl7BliKu', 'value': '23438483'},
  {'dataElement': 'm2afIjMnymV', 'value': '32507297'},
  {'dataElement': 'KUuKOtxzBJ1', 'value': '27386890'},
  {'dataElement': 'RGXZgVrOQyo', 'value': '22404848'},
  {'dataElement': 'qAM23M0qOId', 'value': '24185949'},
  {'dataElement': 'lTiuuQij9HP', 'value': '35586301'},
  {'dataElement': 'f45l3xKDAPs', 'value': '32106705'},
  {'dataElement': 'dKzr3MsO9kG', 'value': '27163954'},
  {'dataElement': 'PIeQekpD664', 'value': '21707821'},
  {'dataElement': 'v2FeCwrKNt5', 'value': '31953030'},
  {'dataElement': 'I5V4NUxtTre', 'value': '14261152'},
  {'dataElement': 'RAQCr5DpCzC', 'value': '2278218'},
  {'dataElement': 'bHSkKIwVBay', 'value': '29305367'},
  {'dataElement': 'iuh5hm4RVBR', 'value': '17821316'},
  {'dataElement': 'qqqAULiKFu2', 'value': '40321193'},
  {'dataElement': 'rl1SLaRmaZ4', 'value': '12446506'},
  {'dataElement': 'f3MTBlkGjZw', 'value': '13922440'},
  {'dataElement': 'MbAkHOTlcyp', 'value': '31134176'},
  {'dataElement': 'n1iUA7kb0wj', 'value': '17779235'},
  {'dataElement': 'lo0rfBSWDbf', 'value': '36828281'},
  {'dataElement': 'rVi7C4a14jp', 'value': '38134177'},
  {'dataElement': 'ZOVJGcrCdCH', 'value': '3661188'},
  {'dataElement': 'BSyp9DU4HWn', 'value': '4133342'},
  {'dataElement': 'ezlLC4UCA2g', 'value': '3275967'},
  {'dataElement': 'hi5J0vMBrbE', 'value': '14800172'},
  {'dataElement': 'FMM88mSULsl', 'value': '24366391'},
  {'dataElement': 'I11IpNMGxaR', 'value': '41174696'},
  {'dataElement': 'sjd8VtIZxmz', 'value': '23489118'},
  {'dataElement': 'KGWccjjpSdP', 'value': '35993176'},
  {'dataElement': 'Q1xDDDusLwl', 'value': '8106978'},
  {'dataElement': 'v1n8aztMcYN', 'value': '910084'},
  {'dataElement': 'XRFwVZNgo0p', 'value': '22109348'},
  {'dataElement': 'b0IzLHcVdm0', 'value': '33124622'},
  {'dataElement': 'lXepqiS7wQi', 'value': '20520281'},
  {'dataElement': 'dbdfZyjDco2', 'value': '32309313'},
  {'dataElement': 'k2hYvS8LTFl', 'value': '22223283'},
  {'dataElement': 'xfkxDz03AFK', 'value': '1334263'},
  {'dataElement': 'PR3HRX1IEBj', 'value': '36658949'},
  {'dataElement': 'KNruIU8QeKP', 'value': '9174238'},
  {'dataElement': 'LszjUZCLWP2', 'value': '27038835'},
  {'dataElement': 'BYXzAABOEbr', 'value': '27185428'},
  {'dataElement': 'I3570OWVcKN', 'value': '19658642'},
  {'dataElement': 'ClUDerxOIWR', 'value': '26134015'},
  {'dataElement': 'jUaZniVe1Uq', 'value': '7354035'}]}

In [92]:
session = auth_dhis("http://localhost:8080")
dataset_id = "OTvkNTijYQY"
url = "http://localhost:8080/api/validationRules?dataSet=" + dataset_id
response = session.get(url)

In [93]:
json.loads(response.text)['validationRules']

[{'displayName': 'IDS - Cholera Confirmed <= Suspected', 'id': 'ri5sW0Ode8z'},
 {'displayName': 'IDS - Diarrhea with Blood (Shigella) Confirmed <= Suspected',
  'id': 'DBV9gBBjU6j'},
 {'displayName': 'IDS - Confirmed AFP (WPV)', 'id': 'Kmowg4bHtx3'},
 {'displayName': 'IDS - Yellow Fever Confirmed <= Suspected',
  'id': 'RJuydwYrXsh'},
 {'displayName': 'IDS - Cholera RDT positive', 'id': 'NuZCTdX9v1V'},
 {'displayName': 'IDS - Pertussis Confirmed <= Suspected',
  'id': 'Lhd8iBuqhei'},
 {'displayName': 'IDS - Probable Yellow Fever', 'id': 'CJbk0vtamtZ'},
 {'displayName': 'IDS - Confirmed Rabies', 'id': 'LjGqJZyl4mV'},
 {'displayName': 'IDS - Plague Confirmed <= Suspected', 'id': 'YspgfwkxwbP'},
 {'displayName': 'IDS - Confirmed AFP (VDPV)', 'id': 'GrtCR8t9S2H'},
 {'displayName': 'IDS - Confirmed Rubella', 'id': 'Akmfhxnv10d'},
 {'displayName': 'IDS - Rabies Confirmed <= Suspected', 'id': 'jpBIpMwYzJT'},
 {'displayName': 'IDS - Viral Hemorrhagic Fever Confirmed <= Suspected',
  'id': 'T078y6B1Xlh'},
 {'displayName': 'IDS - AFP Confirmed<=Suspected', 'id': 'J4MZYb0NmBi'},
 {'displayName': 'IDS - Diphtheria Confirmed <= Suspected',
  'id': 'mGUBTPzD6tC'},
 {'displayName': 'IDS - Meningitis Confirmed <= Suspected',
  'id': 'NX0fbWwP65j'},
 {'displayName': 'IDS - Confirmed Dengue Fever', 'id': 'PRkubegaucB'},
 {'displayName': 'IDS - Acute Watery Diarrhea Confirmed<=Suspected',
  'id': 'I4vXbymh6Jx'},
 {'displayName': 'IDS - Measles Confirmed <= Suspected', 'id': 'bLIghiutoMa'},
 {'displayName': 'IDS - Dengue Fever Confirmed <= Suspected',
  'id': 'a0oHHkZYMCQ'}]

In [ ]:
def validation_adjust(dataElement_df,validation_row):

In [ ]:
dataValue =

In [72]:
dataElements.loc[dataElements['id']== 'v2FeCwrKNt5']

,id,code,name,shortName,description,formName,valueType,domainType,aggregationType,categoryCombo.id,value
54,v2FeCwrKNt5,NaN,IDS One death from severe AWD in a person > 5 ...,One death from severe AWD in a person 5 y+,NaN,NaN,INTEGER_ZERO_OR_POSITIVE,AGGREGATE,SUM,bjDvmb4bfuf default,5

In [96]:
session = auth_dhis("http://localhost:8080")

response = session.get("http://localhost:8080/api/dataAnalysis/validationRules")